### ISSUE TITLE
"03 Data ADO" demo compile error

### ISSUE THREAD

**Issue by IL2** [stijnsanders/xxm#1]
Here it is:
Embarcadero Delphi for Win32 compiler version 30.0
Copyright (c) 1983,2015 Embarcadero Technologies, Inc.
C:\Program Files\IIS Express\WebSite1\xxm\03 Data ADO\xxmData.pas(295) Error: E2033 Types of actual and formal var parameters must be identical
C:\Program Files\IIS Express\WebSite1\xxm\03 Data ADO\xxmData.pas(522) Error: E2033 Types of actual and formal var parameters must be identical
C:\Program Files\IIS Express\WebSite1\xxm\03 Data ADO\xxmSession.pas(46) Fatal: F2063 Could not compile used unit 'xxmData.pas'

**Comment by IL2** [comment]
Problem is executing
cmd.Execute(v,EmptyParam,0);
but second parameter in Execute is defined using var
function Execute(out RecordsAffected: OleVariant; var Parameters: OleVariant; Options: Integer): Recordset15; safecall;

**Comment by stijnsanders** [comment]
Ah yes. I've noticed newer Delphi versions have done something strange to `EmptyParam`. You can fix this for now just by adding a local `var v1:OleVariant;` then first `v1:=EmptyParam;` and then use that v1 instead of EmptyParam. I need it investigate further, but I guess `Null` could work also.

**Comment by IL2** [comment]
You are correct EmptyParam is declared as function since XE6 http://www.desiderata.com.au/blog/?p=652 in System.Variants.pas:
function EmptyParam: OleVariant;
begin
  SetClearVarToEmptyParam(TVarData(Result));
end;
var v1:OleVariant;
v1:=EmptyParam;
is a correct way of using EmptyParam for function calls with vars.

**Comment by stijnsanders** [comment]
I'll close this issue for now, and note down that maybe later I'll add `var v:OleVariant; v:=EmptyParam;` to the source. I've checked a project at work where we had the same problem, and there we settled for `cmd.Execute(cmdText,POleVariant(nil)^,0)` which also works (but is very, very ugly)...
